### ISSUE TITLE
Invalid move packet received

### ISSUE THREAD

**Issue by speedAccount2** [phase/PhaseBot#27]
hi, i must move my bot, but i can't, why?
                                    player.getBot().jump(player.getX(),player.getY(),player.getZ());
bot has been kicked with reason:

Invalid move packet received 

@phase

**Comment by speedAccount2** [comment]
it same with move, moveTo etc.

**Comment by phase** [comment]
I literally have no idea what you are talking about.

> hi, i must move my bot, but i can't, why?
> player.getBot().jump(player.getX(),player.getY(),player.getZ());

I can not answer "_why_" because I have no context to judge what is going wrong.
One line of code that has nothing in it but the call site doesn't allow me to debug anything.

I don't even know if you're using my code! If you are using my code, don't! It's all old and
outdated. Most the algorithms should work, but most of this was just testing.

**Comment by speedAccount2** [comment]
so, where i can find bots with movement etc?
@phase
